name: Docker Image CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag img-name:${{ github.sha}}
      - name: push to docker registry
        with:
          login-server: ${{ secrets.DOCKER_HUB_REGISTRY_NAME }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        run: docker push ${{ secrets.DOCKER_HUB_REGISTRY_NAME }}/img-name:${{ github.sha }}
